name: build UNOFFICIAL

on:
  schedule:
    - cron: "20 6 * * *"
  workflow_dispatch:
  push:
    branches: master

jobs:
  DH:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v4.1.1
        with:
          ref: master
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          git checkout origin/util -- Dockerfile .yarnrc
          docker buildx build --push \
          --tag iamklh/xbvr:nightly \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
  GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v4.1.1
        with:
          ref: master
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Grab Dockerfile
        run: |
          git checkout origin/util -- Dockerfile .yarnrc
      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
#          context: .
#          file: refs/remotes/origin/util/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/unrealklh/xbvr:nightly        
  PUSH:
    needs: [DH, GHCR]
    runs-on: ubuntu-latest
    if: ${{github.event.action == 'push' }}
    steps:
      - uses: actions/checkout@v4.1.1 # required to clone your code
      - name: Report Pushing
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: 'MASTER has been updated!'      

